### ISSUE TITLE
MAYDAY STYLING ISNT BEING WATCHED ?

### ISSUE THREAD

**Issue by ErinYoungkim** [VanessaKasminoff/fitTrackr#9]
so chase and i were up late trying to do landing page/login 
I was able to run the server and the sass but I realized sass wasn't watching my files I created but gave me error codes when I wasn't importing correctly ? so now im not sure what's happening T_T login should be almost done I just need to style it now T_T

**Comment by VanessaKasminoff** [comment]
@ErinYoungkim Did you by chance add `--watch` to your sass compiler command? Also, was it having any errors compiling in general?

**Comment by ErinYoungkim** [comment]
erm i think it was bc i had scr and not src thank you catching that vanessa! :> always a syntax error with me hehe
